
TARGET				:=	remote
TARGET_FOLDER		:=	.

INCLUDE_FOLDERS		+=	../external/preact/
INCLUDE_FOLDERS		+=	../external/ldui/
INCLUDE_FOLDERS		+=	../common/icons/
INCLUDE_FOLDERS		+=	src/

MAIN_JS				:=	src/main.js


# Make this point to the Makefile found in the Carton directory
include ../external/carton/Makefile

# Rules #
fail:
	@echo "[-] Failed to run \"$(TARGET)\"."
