
TARGET				:=	remote
MAIN_JS				:=	src/main.js

LIB_FOLDERS			+=	external/preact
LIB_FOLDERS			+=	external/ldui

INCLUDE_FOLDERS		+=	external/

# Make this point to the Makefile found in the Carton directory
include ../external/carton/Makefile

# Rules #
fail:
	@echo "[-] Failed to run \"$(TARGET)\"."
